version: '3.8'
services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: teste-seplan-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PWD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ${DATABASE_VOLUME_PATH}:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
